# title = "Hugo Themes"
author = "Steve Francia"
copyright = "© Copyright 2023 - Cody Eding. All rights reserved."
paginate = 3
languageCode = "en-us"
DefaultContentLanguage = "en-us"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
baseURL = "https://codyeding.com/"
theme = "hyde"
title = "Cody Eding"
disqusShortname = "codyeding"

[params]
  color = 'gray'

  twitter = 'edingc'
  github = 'edingc'
  instagram = 'edingc'

  avatar = 'cody.eding@gmail.com'
  name = 'Cody Eding'
  bio = 'Test biography.'
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

 # [[menu.main]]
 #   identifier = "about"
 #   name = "About"
 #   url = "/about/"
 #   weight = 10
 # [[menu.main]]
 #   identifier = "contact"
 #   name = "Contact"
 #   url = "/contact/"
 #   weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]