baseURL = "https://codyeding.com/"
languageCode = "en-us"
title = "Cody Eding"
theme="archie"
# copyright = "© Cody Eding. All rights reserved." #overridden by child theme
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "codyeding"

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=true # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "The random musings of an IT Solutions Architect."
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
	customcss = ["css/custom.css"]

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/edingc"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

#[[menu.main]]
#name = "About"
#url = "/about"
#weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4